### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by NickEmma** [NickEmma/Recipe-App#11]
There are 2 members in our team. @NickEmma has been assigned to Team Member 1 task, and @adebowale to Team Member 2. Here is the [link](https://github.com/NickEmma/Recipe-App/projects/1) to the project.

**Comment by Davidosky007** [comment]
Hi @NickEmma @ademibowale 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Well-written issue description 👍 
* All information about team members provided 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
